openapi: 3.0.2
info:
  description: "Old World XML Viewer API"
  version: "1"
  title: old-world-xml-viewer


paths:
  /auth/google/redirect:
    get:
      summary: google認証のリダイレクトURLを取得
      responses:
        "200":
          description: '成功'
          content:
            text/html:
              schema:
                type: string
                example: "https://accounts.google.com/o/oauth2/auth"

